import { Theme } from './types';

const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

const radius = {
  sm: 4,
  md: 8,
  lg: 16,
  xl: 24,
  full: 9999,
};

export const themes: Record<string, Theme> = {
  'futuristic-dark': {
    id: 'futuristic-dark',
    name: 'Futuristic Dark',
    description: 'Sleek dark UI with cyan accents',
    glowEnabled: true,
    spacing,
    radius,
    shadow: {
      color: '#00d4ff',
      offset: { width: 0, height: 4 },
      opacity: 0.3,
      radius: 12,
      elevation: 8,
    },
    colors: {
      primary: '#00d4ff',
      secondary: '#0066ff',
      accent: '#7c3aed',
      background: '#0a0a1a',
      surface: '#111128',
      surfaceAlt: '#1a1a35',
      text: '#e8f4ff',
      textSecondary: '#8892b0',
      textMuted: '#4a5568',
      border: '#1e2a45',
      borderAlt: '#00d4ff33',
      success: '#00ff88',
      warning: '#ffaa00',
      error: '#ff4455',
      info: '#00aaff',
      gradientStart: '#0a0a1a',
      gradientEnd: '#111128',
      tabBar: '#0d0d22',
      tabBarActive: '#00d4ff',
      tabBarInactive: '#4a5568',
      card: '#111128',
      cardBorder: '#1e2a45',
      scanOverlay: 'rgba(0,212,255,0.15)',
      priceUp: '#00ff88',
      priceDown: '#ff4455',
      priceStable: '#ffaa00',
    },
  },
  'futuristic-light': {
    id: 'futuristic-light',
    name: 'Futuristic Light',
    description: 'Clean light UI with blue accents',
    glowEnabled: false,
    spacing,
    radius,
    shadow: {
      color: '#0066ff',
      offset: { width: 0, height: 2 },
      opacity: 0.1,
      radius: 8,
      elevation: 4,
    },
    colors: {
      primary: '#0066ff',
      secondary: '#4d94ff',
      accent: '#7c3aed',
      background: '#f0f4ff',
      surface: '#ffffff',
      surfaceAlt: '#e8eeff',
      text: '#0a1628',
      textSecondary: '#4a5568',
      textMuted: '#a0aec0',
      border: '#dde4f0',
      borderAlt: '#0066ff33',
      success: '#00aa55',
      warning: '#dd8800',
      error: '#cc2233',
      info: '#0066cc',
      gradientStart: '#f0f4ff',
      gradientEnd: '#e8eeff',
      tabBar: '#ffffff',
      tabBarActive: '#0066ff',
      tabBarInactive: '#a0aec0',
      card: '#ffffff',
      cardBorder: '#dde4f0',
      scanOverlay: 'rgba(0,102,255,0.1)',
      priceUp: '#00aa55',
      priceDown: '#cc2233',
      priceStable: '#dd8800',
    },
  },
  'anime-neon': {
    id: 'anime-neon',
    name: 'Anime Neon',
    description: 'Vibrant neon colors with glow effects',
    glowEnabled: true,
    spacing,
    radius: { ...radius, md: 12, lg: 20, xl: 28 },
    shadow: {
      color: '#ff00ff',
      offset: { width: 0, height: 4 },
      opacity: 0.5,
      radius: 16,
      elevation: 12,
    },
    colors: {
      primary: '#ff00ff',
      secondary: '#00ffff',
      accent: '#ffff00',
      background: '#080010',
      surface: '#120020',
      surfaceAlt: '#1a0030',
      text: '#ffffff',
      textSecondary: '#cc99ff',
      textMuted: '#664488',
      border: '#330055',
      borderAlt: '#ff00ff44',
      success: '#00ff88',
      warning: '#ffff00',
      error: '#ff2266',
      info: '#00ccff',
      gradientStart: '#080010',
      gradientEnd: '#1a0030',
      tabBar: '#0d0018',
      tabBarActive: '#ff00ff',
      tabBarInactive: '#664488',
      card: '#120020',
      cardBorder: '#330055',
      scanOverlay: 'rgba(255,0,255,0.2)',
      priceUp: '#00ff88',
      priceDown: '#ff2266',
      priceStable: '#ffff00',
    },
  },
  'anime-pastel': {
    id: 'anime-pastel',
    name: 'Anime Pastel',
    description: 'Soft kawaii colors, gentle and cute',
    glowEnabled: false,
    spacing,
    radius: { ...radius, md: 16, lg: 24, xl: 32, sm: 8 },
    shadow: {
      color: '#ff80aa',
      offset: { width: 0, height: 2 },
      opacity: 0.15,
      radius: 8,
      elevation: 3,
    },
    colors: {
      primary: '#ff80aa',
      secondary: '#80aaff',
      accent: '#aa80ff',
      background: '#fff5fa',
      surface: '#ffffff',
      surfaceAlt: '#fff0f5',
      text: '#2a1a2e',
      textSecondary: '#8866aa',
      textMuted: '#ccaacc',
      border: '#ffd0e8',
      borderAlt: '#ff80aa44',
      success: '#80ddaa',
      warning: '#ffcc80',
      error: '#ff8080',
      info: '#80aaff',
      gradientStart: '#fff5fa',
      gradientEnd: '#f5eeff',
      tabBar: '#ffffff',
      tabBarActive: '#ff80aa',
      tabBarInactive: '#ccaacc',
      card: '#ffffff',
      cardBorder: '#ffd0e8',
      scanOverlay: 'rgba(255,128,170,0.15)',
      priceUp: '#80ddaa',
      priceDown: '#ff8080',
      priceStable: '#ffcc80',
    },
  },
  'cyberpunk': {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon on dark, glitch-style aesthetics',
    glowEnabled: true,
    spacing,
    radius: { ...radius, sm: 0, md: 2, lg: 4, xl: 6 },
    shadow: {
      color: '#ffff00',
      offset: { width: 2, height: 4 },
      opacity: 0.6,
      radius: 0,
      elevation: 10,
    },
    colors: {
      primary: '#ffff00',
      secondary: '#ff0066',
      accent: '#00ffff',
      background: '#050505',
      surface: '#0f0f0f',
      surfaceAlt: '#1a0a00',
      text: '#ffff00',
      textSecondary: '#ff9900',
      textMuted: '#664400',
      border: '#333300',
      borderAlt: '#ffff0055',
      success: '#00ff00',
      warning: '#ff9900',
      error: '#ff0033',
      info: '#00ffff',
      gradientStart: '#050505',
      gradientEnd: '#0f0f0f',
      tabBar: '#080808',
      tabBarActive: '#ffff00',
      tabBarInactive: '#664400',
      card: '#0f0f0f',
      cardBorder: '#333300',
      scanOverlay: 'rgba(255,255,0,0.15)',
      priceUp: '#00ff00',
      priceDown: '#ff0033',
      priceStable: '#ff9900',
    },
  },
  'ninja': {
    id: 'ninja',
    name: 'PriceNinja',
    description: 'Silent. Sharp. Shadow. The way of the Ninja.',
    glowEnabled: true,
    spacing,
    radius: { ...radius, sm: 2, md: 4, lg: 8, xl: 12 },
    shadow: {
      color: '#00ff88',
      offset: { width: 0, height: 2 },
      opacity: 0.4,
      radius: 10,
      elevation: 10,
    },
    colors: {
      primary: '#00ff88',
      secondary: '#39ff14',
      accent: '#ff3300',
      background: '#080808',
      surface: '#101010',
      surfaceAlt: '#181818',
      text: '#e8f5e8',
      textSecondary: '#7abf7a',
      textMuted: '#3a5a3a',
      border: '#1e2e1e',
      borderAlt: '#00ff8844',
      success: '#00ff88',
      warning: '#ffaa00',
      error: '#ff3300',
      info: '#00ccff',
      gradientStart: '#080808',
      gradientEnd: '#101a10',
      tabBar: '#060606',
      tabBarActive: '#00ff88',
      tabBarInactive: '#3a5a3a',
      card: '#101010',
      cardBorder: '#1e2e1e',
      scanOverlay: 'rgba(0,255,136,0.12)',
      priceUp: '#00ff88',
      priceDown: '#ff3300',
      priceStable: '#ffaa00',
    },
  },
  'minimal-clean': {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    description: 'Simple, clean, distraction-free',
    glowEnabled: false,
    spacing,
    radius,
    shadow: {
      color: '#000000',
      offset: { width: 0, height: 1 },
      opacity: 0.08,
      radius: 4,
      elevation: 2,
    },
    colors: {
      primary: '#2563eb',
      secondary: '#64748b',
      accent: '#059669',
      background: '#ffffff',
      surface: '#f8fafc',
      surfaceAlt: '#f1f5f9',
      text: '#0f172a',
      textSecondary: '#475569',
      textMuted: '#94a3b8',
      border: '#e2e8f0',
      borderAlt: '#2563eb33',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
      info: '#0284c7',
      gradientStart: '#ffffff',
      gradientEnd: '#f8fafc',
      tabBar: '#ffffff',
      tabBarActive: '#2563eb',
      tabBarInactive: '#94a3b8',
      card: '#ffffff',
      cardBorder: '#e2e8f0',
      scanOverlay: 'rgba(37,99,235,0.08)',
      priceUp: '#059669',
      priceDown: '#dc2626',
      priceStable: '#d97706',
    },
  },
};

export const defaultThemeId = 'ninja';
